//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboCup.AtHome.GPSRCmdGen {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoboCup.AtHome.GPSRCmdGen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 #
        ///# This grammar file has no main, therefore, cannot be loaded
        ///# standalone. Import using:
        ///# ; import common.txt
        ///#
        ///# The following rules must be defined in the importer
        ///# ; An object type
        ///# $object
        ///# ; Rule for finding a specific (named) person
        ///# $findp
        ///# ; A named or described person in the given place
        ///# $whowhere
        ///#
        ///; grammar name Common
        ///
        ///##############################################################################
        ///#
        ///# Manipulation
        ///#
        ///######################################################################## [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CommonRules {
            get {
                return ResourceManager.GetString("CommonRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ../../CommonFiles/FormatSpecification.txt 的本地化字符串。
        /// </summary>
        internal static string FormatSpecification {
            get {
                return ResourceManager.GetString("FormatSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ../../CommonFiles/Gestures.xml 的本地化字符串。
        /// </summary>
        internal static string Gestures {
            get {
                return ResourceManager.GetString("Gestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ; grammar name GPSR Grammar
        ///; grammar tier High
        ///; import common.txt
        ///
        ///$Main     = $pmain | $main
        ///$pmain    = $polite $main
        ///
        ///$main     = $fndppl
        ///$main     = $fndobj
        ///$main     = $guide
        ///$main     = $follow
        ///$main     = $followout
        ///$main     = $incomplete
        ///$main     = $man
        ///$main     = $complexman
        ///$main     = $partyhost
        ///
        ///##############################################################################
        ///#
        ///# Production Rules required by common.txt
        ///#
        ///######################################################################### [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GPSRGrammar {
            get {
                return ResourceManager.GetString("GPSRGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ##############################################################################
        ///#
        ///# Category1 Grammar
        ///# 
        ///# Author:  Mauricio Matamoros
        ///# Date:    April 2017
        ///#
        ///# IMPORTANT: 
        ///# Since this document declares a grammar for generating sentences,
        ///# NO RECURSIVE rules shall be used.
        ///# 
        ///##############################################################################
        ///
        ////********************************************************************
        ///*
        ///* FORMAT
        ///*
        ///*********************************************************************
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GPSRGrammarCat1 {
            get {
                return ResourceManager.GetString("GPSRGrammarCat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ../../CommonFiles/GrammarHeader.txt 的本地化字符串。
        /// </summary>
        internal static string GrammarHeader {
            get {
                return ResourceManager.GetString("GrammarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ../../CommonFiles/Locations.xml 的本地化字符串。
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ../../CommonFiles/Names.xml 的本地化字符串。
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ../../CommonFiles/Objects.xml 的本地化字符串。
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ../../CommonFiles/Questions.xml 的本地化字符串。
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
    }
}
